apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    sidecar.jaegertracing.io/inject: 'true'
    prometheus.io/scrape: "true"
    prometheus.io/path: /metrics
    prometheus.io/port: frontend
  name: frontend
  labels:
    name: frontend
    release: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: lynettemidy/frontend:v1
          imagePullPolicy: Always
          env:
            - name: COUNTER_ENDPOINT
              value: "http://do-visit-counter-backend.default.svc.cluster.local:8081"
            - name: JAEGER_HOST
              value: "my-traces-agent.observability.svc.cluster.local"
          ports:
            - name: frontend
              containerPort: 8080
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  selector:
    app: frontend
  ports:
    - name: frontend
      protocol: TCP
      port: 8080
      targetPort: frontend
  type: LoadBalancer
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  annotations:
    sidecar.jaegertracing.io/inject: 'true'
    prometheus.io/scrape: "true"
    prometheus.io/path: /metrics
    prometheus.io/port: frontend
  name: frontend
  namespace: monitoring
  labels:
    app: frontend
    release: prometheus
spec:
  selector:
    matchLabels:
      app: frontend
  endpoints:
    - port: frontend
      path: /metrics
      interval: 15s
  namespaceSelector:
    matchNames:
      - default