apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    sidecar.jaegertracing.io/inject: 'true'
    prometheus.io/scrape: "true"
    prometheus.io/path: /metrics
    prometheus.io/port: trialport
  name: trial
  labels:
    name: trial
    release: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trial
  template:
    metadata:
      labels:
        app: trial
    spec:
      containers:
        - env:
            - name: JAEGER_HOST
              value: my-traces-agent.observability.svc.cluster.local
          image: lynettemidy/trial:v1.0.0
          imagePullPolicy: Always
          name: trial
          ports:
            - name: trailport
              containerPort: 8080
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: trial
  labels:
    app: trial
spec:
  selector:
    app: trial
  ports:
    - name: trial
      protocol: TCP
      port: 8082
      targetPort: trialport
  type: LoadBalancer
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: trial
  namespace: monitoring
  labels:
    app: trial
    release: prometheus
spec:
  selector:
    matchLabels:
      app: trial
  endpoints:
    - port: trial
      path: /metrics
      interval: 15s
  namespaceSelector:
    matchNames:
      - default